name: 'TCA'
on: [push]

jobs:
  CodeAnalysis:
    runs-on: ubuntu-latest
    name: Tencent Cloud Code Analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: TCA
        uses: zthzhang111/tca_action_demo@v1.1.5
        with:
          label: 'open_source_check'
